acs:
  state: 'Florida'
  year: 2018
  tableIDs: 
    - 'B01003_001E'
    - 'B02001_001E'
    - 'B02001_002E'
    - 'B12001_004E'
    - 'B12001_001E'
    - 'B12001_013E'
    - 'B15003_022E'
    - 'B15003_023E'
    - 'B15003_024E'
    - 'B15003_025E'
    - 'B15003_001E'  
    - 'B22010_001E'
    - 'B22010_002E'
    - 'B29001_005E'
    - 'B21002_007E'
    - 'B23025_001E'
    - 'B23025_007E'
    - 'B28011_001E'
    - 'B28011_008E'
    - 'B29003_001E' 
    - 'B29003_002E'
    - 'B29004_001E'
    - 'B29002_007E'
    - 'B29002_008E'
    - 'B29002_001E'
  variables:
    - 'total_population'
    - 'percent_white' 
    - 'percent_married'
    - 'percent_college_degree_higher'
    - 'vietnam_war_veterans'
    - 'percent_food_stamp'
    - 'percent_unemployed'
    - 'percent_no_internet'
    - 'voter_65yr_and_over'
    - 'voter_percent_college_degree_higher'
    - 'voter_percent_below_poverty'
    - 'voter_median_income'